[QSP-02] Burn Valid Passports
QuadrataNetwork/passport-contracts pull request #139
Opened 2022-09-14 18:25 UTC by teddy-quadrata

## Description
QPQ-02: if issuerA attests COUNTRY, DID, etc… to accountA, and issuerB tries deleting accountA with nothing attested, then isEmpty will remain true and the passport will be deleted with all the attributes from issuerA still alive.

Solution: check that all attribute data gets deleted before burning the passport.

## Checklist
1. [x] Unit Testing
2. [x] Backward Compatible
3. [x] Upgrade Safe (storage)
4. [N/A] Updated Confluence
5. [N/A] Updated Gitbook

2022-09-15 21:48 UTC, faze-quadrata commented on contracts/QuadPassport.sol
> -                if (attrs.length > 0) {
Add test?

2022-09-16 01:29 UTC, fabrice-quadrata requested changes
require unit tests

2022-09-16 18:14 UTC, teddy-quadrata commented on contracts/QuadPassport.sol
> -                if (attrs.length > 0) {
added test

2022-09-16 19:30 UTC, fabrice-quadrata approved these changes

2022-09-16 20:04 UTC, merged