[QSQ-01] supportsInterface() Not Properly Implemented
QuadrataNetwork/passport-contracts pull request #143
Opened 2022-09-14 21:50 UTC by teddy-quadrata

## Description
QSQ-01: A surplus of interface were incorrectly added to ERC165.
Solution: Ensure supportsInterface is returning all of our implemented function selectors

## Checklist
1. [N/A] Unit Testing
2. [x] Backward Compatible
3. [x] Upgrade Safe (storage)
4. [N/A] Updated Confluence
5. [N/A] Updated Gitbook

2022-09-15 18:30 UTC, faze-quadrata approved these changes

2022-09-16 01:23 UTC, fabrice-quadrata commented on contracts/QuadSoulbound.sol
> +            interfaceId == type(IQuadSoulbound).interfaceId ||
I don't think that's what they asked for.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.4.2/contracts/utils/introspection/ERC165.sol

2022-09-16 01:26 UTC, fabrice-quadrata requested changes
Still not properly implemented.

I believe you need to inherit from ERC165 + support

2022-09-16 17:49 UTC, teddy-quadrata commented on contracts/QuadSoulbound.sol
> +            interfaceId == type(IQuadSoulbound).interfaceId ||
Fixed; you are right. Now I've added our functions + IERC165.

2022-09-16 22:02 UTC, fabrice-quadrata approved these changes

2022-09-22 21:18 UTC, closed without merging