Helper functions
QuadrataNetwork/passport-contracts pull request #158
Opened 2022-12-07 00:52 UTC by faze-quadrata

## Description

## Checklist
1. [ ] Unit Testing?
2. [ ] Backward Compatible?
3. [ ] Upgrade Safe (storage)?
4. [ ] Updated Confluence?
5. [ ] Updated Gitbook?

2022-12-07 22:24 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +  function IsBusinessTrue(bytes32 _attrValue) public pure returns (bool) {
docstring everywhere if possible

2022-12-07 22:25 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +  function CredProtocolScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHash, uint256 _iteratorThreshold) public pure returns (bool){
You mean TU?

2022-12-07 22:30 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +    for(uint256 i = 0; i < 100; i++){
100 is a placeholder right? We wouldn't want to iterate 100 times to find out it's not enough?

2022-12-07 22:31 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +  function CredProtocolScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHash, uint256 _iteratorThreshold) public pure returns (bool){
_startingHiddenScore

2022-12-07 22:32 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +  function IsBusinessTrue(bytes32 _attrValue) public pure returns (bool) {
added

2022-12-07 22:32 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +  function CredProtocolScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHash, uint256 _iteratorThreshold) public pure returns (bool){
yes

2022-12-07 22:32 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +  function CredProtocolScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHash, uint256 _iteratorThreshold) public pure returns (bool){
Need to handle the case whre _attrValue == bytes32(0)

2022-12-07 22:32 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +  function CredProtocolScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHash, uint256 _iteratorThreshold) public pure returns (bool){
will update

2022-12-07 22:32 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +  }
We're missing the CredProtocolScore helper

2022-12-07 22:33 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +    for(uint256 i = 0; i < 100; i++){
It depends on the number of tiers we'll have. Open to suggestions

2022-12-07 22:34 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +    for(uint256 i = 0; i < 100; i++){
it should probably be total number of tiers +[2-5]? dunno might want to ping @travis-quadrata about his input

2022-12-07 22:39 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +  function IsBusinessFalse(bytes32 _attrValue) public pure returns (bool) {
yes. fixed

2022-12-07 22:45 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +  }
added

2022-12-07 23:02 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +  function TuCreditScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHiddenScore, uint256 _iteratorThreshold) public pure returns (bool){
can we rename this VantageScore (to confirm with Springlabs) that this is the data being posted

2022-12-07 23:03 UTC, fabrice-quadrata commented on contracts/utility/QueryUtils.sol
> +library QueryUtils {
Is there a good way to handle upgrade for Libraries?

How are we gonna append new functions?

New deployments with versioning?

2022-12-07 23:09 UTC, teddy-quadrata requested changes

2022-12-07 23:09 UTC, teddy-quadrata commented on contracts/tests/TestQueryUtils.sol
> +    function CountryIsEqual(bytes32 _attrValue, string memory _expectedString) public pure returns(bool) {
Nit: Why are we starting function names with a capital letter? Seems to violate conventions no?

2022-12-07 23:09 UTC, teddy-quadrata commented on contracts/utility/QueryUtils.sol
> +    for(uint256 i = 0; i < 25; i++){
Hardcoding 25 won't work if our table is larger. We need to know the table length

2022-12-07 23:09 UTC, teddy-quadrata commented on contracts/utility/QueryUtils.sol
> +  function VantageScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHiddenScore, uint256 _iteratorThreshold) public pure returns (bool){
This looks to be doing a greater than check.

2022-12-07 23:12 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +  function VantageScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHiddenScore, uint256 _iteratorThreshold) public pure returns (bool){
it's checking that the iterator counter is less than the bucket threshold count

2022-12-07 23:12 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +  function VantageScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHiddenScore, uint256 _iteratorThreshold) public pure returns (bool){
the person calling this function isnt passing in the vantage score, they are passing in the number of max hashes

2022-12-07 23:15 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +    for(uint256 i = 0; i < 25; i++){
yes i've already pinged @travis-quadrata

2022-12-07 23:15 UTC, faze-quadrata commented on contracts/tests/TestQueryUtils.sol
> +    function CountryIsEqual(bytes32 _attrValue, string memory _expectedString) public pure returns(bool) {
updated

2022-12-08 00:04 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +library QueryUtils {
i'll look into this

2022-12-08 00:08 UTC, faze-quadrata commented on contracts/utility/QueryUtils.sol
> +  function TuCreditScoreIteratorLessThan(bytes32 _attrValue, bytes32 _startingHiddenScore, uint256 _iteratorThreshold) public pure returns (bool){
yes

2022-12-08 19:24 UTC, teddy-quadrata approved these changes

2022-12-08 19:25 UTC, teddy-quadrata commented on contracts/utility/QueryUtils.sol
> +library QueryUtils {
integrator logic contract will be linked with newest version of Quadrata/contracts npm package. no need for us to do anything special other than update npm package

2022-12-08 22:11 UTC, merged