Social Attributes
QuadrataNetwork/passport-contracts pull request #162
Opened 2022-12-14 22:39 UTC by faze-quadrata

## Description

## Checklist
1. [ ] Unit Testing?
2. [ ] Backward Compatible?
3. [ ] Upgrade Safe (storage)?
4. [ ] Updated Confluence?
5. [ ] Updated Gitbook?

2022-12-15 21:14 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    mapping(address=>uint256) public funds;
Nit: Put into storage contract.

2022-12-15 21:26 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        _attributes[attrKey].push(attr);
This looks like a bug. The storage should not be an array because all arrays using this structure will be length 1. Solutions:
1. Change Attribute[] to Attribute in storage layout
2. Or, Remove msg.sender from the key
I believe you meant to remove msg.sender from the key.

2022-12-15 21:30 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        _attributes[attrKey].push(attr);
Also, there needs to be a `require(!governance.eligibleAttributes(_attrName) && !governance.eligibleAttributesByDID(_attrName))` or are we okay with social attribute with same names as in QuadGovernance?

2022-12-15 21:32 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        return !governance.eligibleAttributes(_attrName) && !governance.eligibleAttributesByDID(_attrName);
Bug? This means any attribute that doesn't exist in governance is a social attribute. Shouldn't we check if the social attribute has been posted by anyone first?

2022-12-15 21:33 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        _attributes[attrKey].push(attr);
good catch. will add teh check

2022-12-15 21:34 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        return !governance.eligibleAttributes(_attrName) && !governance.eligibleAttributesByDID(_attrName);
no, we're not reserving attribute names to the first issuer that attests to it

2022-12-15 21:34 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        uint256 quadrataFee;
cleaner syntax:


```
 function calculateSocialFees(address _issuer) view internal returns (uint256 quadrataFee, uint256 issuerFee){
         if(issuerQueryFee[_issuer].div(uint256(2)) > issuerQueryFee[governance.treasury()]) {
             issuerFee = issuerQueryFee[_issuer].div(uint256(2));
             quadrataFee = issuerQueryFee[_issuer] - issuerFee;
         }else{
             issuerFee = issuerQueryFee[_issuer].div(uint256(2));
             quadrataFee = issuerQueryFee[governance.treasury()];
         }
     }
```

2022-12-15 21:34 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        return !governance.eligibleAttributes(_attrName) && !governance.eligibleAttributesByDID(_attrName);
it's also the reason why i had msg.sender (issuer) hashed as the key for _attributes

2022-12-15 21:36 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function allowAddress(address _addr, bool _allow) public {
Nit: I personally like the names: approve/allowance instead of allowList. allowList sounds like anyone who is allowed is an admin. That's what avalanche means by their allowList.

2022-12-15 21:42 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        payable(msg.sender).transfer(amount);
transfer is bad practice, they require hard value of 2300 gas. instead opt for:

```
(bool success, ) = recipient.call{value:amount}("");
require(success, "Transfer failed.");
```

2022-12-15 21:49 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +                fee += (interimIssuer+interimQuadrata);
It looks like there's a vector where malicious user can overflow fee and drain the contract.

2022-12-15 21:50 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +                fee += (interimIssuer+interimQuadrata);
use SafeMath or check for under/over flow

2022-12-15 21:59 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    mapping(address=>mapping(address=>bool)) public allowList;
Do we want to store allowList? or should we do one-time ?

2022-12-15 22:00 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    mapping(address=>uint256) public issuerQueryFee;
probably issuer+attrType query fee.

mapping(bytes32 => uint256)

2022-12-15 22:01 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        issuerQueryFee[governance.treasury()] = _quadrataQueryFee;
I would store this as a single variable `minGlobalQueryFee`

Not sure we need to set it in the constructor, let's use admin method (like the other contracts)

2022-12-15 22:02 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function writeAttributes(bytes32 _attrName, bytes32 _attrValue, address _targetAddr) public {
I think we need to add a signature in here (signed by the user authorizing [issuer] to post [attrValues] about them)

2022-12-15 22:02 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function writeAttributes(bytes32 _attrName, bytes32 _attrValue, address _targetAddr) public {
the 2nd question is:
do we want to keep this in your allowList to allow future writes or not

2022-12-15 22:03 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        require(_isSocialAttribute(_attrName), 'ATTR_NAME_NOT_ALLOWED');
What's the utility of that?

2022-12-15 22:03 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        _attributes[attrKey].push(attr);
agree with that

2022-12-15 22:10 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function getAttributesBulk(
We will need the Legacy Implementation as well

2022-12-15 22:11 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function setIssuerQueryFee(uint256 _amount) public {
probably need to be per attribute

2022-12-15 22:12 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +contract SocialAttributeReader is UUPSUpgradeable, QuadConstant{
add docstring + events

2022-12-15 22:26 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +                issuerFee += interimIssuer;
Use safe math to prevent overflow contract drain here

2022-12-15 22:51 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        require(_isSocialAttribute(_attrName), 'ATTR_NAME_NOT_ALLOWED');
prevents someone from writing a primary attribute to this contract since they would not be able to query it from this contract anyway. any primary attribute (e.g. COUNTRY, AML) is queried via QuadReader

2022-12-15 22:55 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function writeAttributes(bytes32 _attrName, bytes32 _attrValue, address _targetAddr) public {
maybe we just have them sign over issuer address? signing over both issuer addresses and attrNames means that there's messaging parsing onchain which is a pretty gas intensive operation

2022-12-15 22:56 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function writeAttributes(bytes32 _attrName, bytes32 _attrValue, address _targetAddr) public {
we could have the user sign over keccak(issuerAddr,attrName) but that means that the user is signing over a hash (i.e. he wont know what he's signing)

2022-12-15 23:08 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        issuerQueryFee[governance.treasury()] = _quadrataQueryFee;
done

2022-12-15 23:08 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    mapping(address=>uint256) public issuerQueryFee;
did a mapping of mapping. done

2022-12-15 23:09 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function setIssuerQueryFee(uint256 _amount) public {
done

2022-12-15 23:15 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function queryFee(
there's an extra parameter that needs to be added (issuer address) since the user/dapp need to specify who they are querying from - it's how we handle attribute name collisions

2022-12-15 23:17 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +                issuerFee += interimIssuer;
done

2022-12-15 23:20 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function allowAddress(address _addr, bool _allow) public {
renamed

2022-12-15 23:48 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        return !governance.eligibleAttributes(_attrName) && !governance.eligibleAttributesByDID(_attrName);
resolved

2022-12-20 00:15 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        _attributes[attrKey].push(attr);
updated

2022-12-20 00:15 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        _attributes[attrKey].push(attr);
assumed no history needed

2022-12-20 00:17 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    mapping(address=>mapping(address=>bool)) public allowList;
went with authentication for address to write a specific datatype will be done via signature. once approved once, it will be assumed that issuer address will always have approval (i.e. subsequent writes will not require a valid signature)

2022-12-20 00:18 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function writeAttributes(bytes32 _attrName, bytes32 _attrValue, address _targetAddr) public {
done. see message above

2022-12-20 00:21 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function queryFee(
done

2022-12-20 22:38 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function getAttributesBulk(
added

2022-12-20 23:50 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    mapping(address=>uint256) public funds;
done

2022-12-21 18:16 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +import "hardhat/console.sol";
reminder

2022-12-21 18:16 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    using SafeMath for uint256;
I don't think we need SafeMath anymore for solidity version >0.8

2022-12-21 18:20 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            bytes32 signedMsg = ECDSAUpgradeable.toEthSignedMessageHash(_attrName);
I wouldn't want this to be the signed message.

We need something more visible so that the user doesn't feel scared of signing.

Like "I authorized [0x...] to issue [attrName] to my address [0x...]".

2022-12-21 18:20 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        _attributeStorage[keccak256(abi.encode(_account, _attrName))] = attr;
we likely need the issuer address as part of the key (to avoid issuer overwriting each other values)

2022-12-21 18:21 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        bytes32 _attrName, // keccak(issuerAddr|keccak(attrName))
imo, we should distinguish attrName and issuerAddr == msg.sender

2022-12-21 18:25 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        bytes32 _attrName, // keccak(issuerAddr|keccak(attrName))
hmm nvm.

But rename: attrIssuerName maybe?

2022-12-21 18:29 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function getAttributesBulk(
how much gas does this one cost with 3 attributes?

2022-12-21 18:32 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function getAttributeKey(address _issuer, bytes32 _attrName) public view returns(bytes32){
you should use that function throughout your contract

2022-12-21 18:34 UTC, fabrice-quadrata commented on contracts/storage/QuadSocialAttributeReaderStore.sol
> +    // keccak256(userAddress, attrType))
attrType == issuerAddress, attrName

2022-12-23 01:04 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            bytes32 signedMsg = ECDSAUpgradeable.toEthSignedMessageHash(_attrName);
done

2022-12-23 01:10 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function getAttributeKey(address _issuer, bytes32 _attrName) public view returns(bytes32){
done

2022-12-23 01:10 UTC, faze-quadrata commented on contracts/storage/QuadSocialAttributeReaderStore.sol
> +    // keccak256(userAddress, attrType))
removed comment

2022-12-23 01:10 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        bytes32 _attrName, // keccak(issuerAddr|keccak(attrName))
done

2022-12-27 21:53 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function getAttributesBulk(
142175, see test "succeeds with multiple attributes"

2022-12-27 22:21 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function queryFee(address _account,  bytes32 _attribute) public view returns(uint256){
Any user/integrator of this function can potentially be exploited via overflow attack bc interimIssuer is not validated and set via any actor. Missing SafeMath here or validate interimIssuer - interimQuadrata to be less than UINT256_MAX_INT

2022-12-27 22:21 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +                fee += (interimIssuer+interimQuadrata);
still open

2022-12-27 22:24 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function queryFee(address _account,  bytes32 _attribute) public view returns(uint256){
safemath'd

2022-12-27 22:45 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        values = new bytes32[](1);
Why are we returning arrays when the length is always one?

2022-12-27 22:49 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function toString(address account) internal pure returns(string memory) {
Nit: Should be public or follow _internal convention

2022-12-27 22:51 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            str[2+i*2] = alphabet[uint(uint8(data[i] >> 4))];
Same naming convention as above

Note: I'm skeptical about using this random guy's code. Have we tested it under wide variety of signed messages? Do we understand the purpose and limitations of the bitwise ops?

2022-12-27 22:53 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    ) public view returns(uint256){
```suggestion
    ) public view returns(uint256 fee){
```

2022-12-27 22:53 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        uint256 fee;
```suggestion
```

2022-12-27 22:53 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        uint256 fee;
```suggestion
```

2022-12-27 23:01 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        require(msg.value == quadFeeCounter.add(issuerFeeCounter).add(quadReaderFeeCounter)," INVALID_QUERY_FEE");
This does violate: Checks, Effects, Interactions pattern. If we get this audited, this will get flagged because they won't know what these state-changing external calls are doing. I'm also not sure this violation has any negative consequences. To be safe, adding OZ modifier nonReentrant would completely derisk this violation.

2022-12-27 23:02 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        require(msg.value == (quadFeeCounter.add(issuerFeeCounter).add(quadReaderFeeCounter)), "INVALID_FEE");
same comment as above about nonReentrant

2022-12-27 23:28 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +                fee += (interimIssuer+interimQuadrata);
should be closed

2022-12-27 23:30 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        values = new bytes32[](1);
getAttributesLegacy returns lists. with social attribute we only store a single value but because we have to support "primary" attributes, we need it to be arrays here

2022-12-27 23:30 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            str[2+i*2] = alphabet[uint(uint8(data[i] >> 4))];
no, blind trusting here

2022-12-27 23:35 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        require(msg.value == quadFeeCounter.add(issuerFeeCounter).add(quadReaderFeeCounter)," INVALID_QUERY_FEE");
fixed

2022-12-27 23:35 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        require(msg.value == (quadFeeCounter.add(issuerFeeCounter).add(quadReaderFeeCounter)), "INVALID_FEE");
fixed

2022-12-27 23:54 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            str[2+i*2] = alphabet[uint(uint8(data[i] >> 4))];
I would feel comfortable blind trusting if this was not a smart contract but this is business critical infra.

2022-12-27 23:54 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function toString(address account) internal pure returns(string memory) {
I don't see that this updated

2022-12-27 23:55 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function toString(address _account) internal pure returns(string memory) {
```suggestion
    function toString(address _account) public pure returns(string memory) {
```

2022-12-27 23:55 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function toString(address _account) internal pure returns(string memory) {
```suggestion
    function toString(address _account) public pure returns(string memory) {
```

2022-12-27 23:55 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function toString(bytes memory _data) internal pure returns(string memory) {
```suggestion
    function toString(bytes memory _data) public pure returns(string memory) {
```

2022-12-27 23:55 UTC, teddy-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function toString(bytes memory _data) internal pure returns(string memory) {
```suggestion
    function toString(bytes memory _data) public pure returns(string memory) {
```

2022-12-28 19:07 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    using SafeMath for uint256;
@faze-quadrata

2022-12-28 19:11 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            bytes memory message = abi.encodePacked("I authorize ", Strings.toHexString(uint256(uint160(msg.sender)), 20), " to attest to my address ", Strings.toHexString(uint256(uint160(_account)),
Did we confirm with Jeff that this is the message we want?

2022-12-28 19:11 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function setAttributes(
What's the gas cost for this function?

2022-12-28 19:11 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        bytes32 _attrIssuerName, // keccak(issuerAddr|keccak(attrName))
attrAndIssuer better name?

2022-12-28 19:11 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function getAttributes(
Gas cost for this one?

2022-12-28 19:20 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            bytes memory message = abi.encodePacked("I authorize ", Strings.toHexString(uint256(uint160(msg.sender)), 20), " to attest to my address ", Strings.toHexString(uint256(uint160(_account)),
no, pinged

2022-12-28 22:11 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function getAttributes(
123736

2022-12-28 22:11 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    function setAttributes(
137820

2022-12-29 19:50 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            bytes memory message = abi.encodePacked("I authorize ", Strings.toHexString(uint256(uint160(msg.sender)), 20), " to attest to my address ", Strings.toHexString(uint256(uint160(_account)),
signed off w/ jeff on messaging

2023-01-06 18:42 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    /// note The _sigAccount is a one-time use key (per attribute) to enable writing
There's a @notice if you want to use that

2023-01-06 18:56 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        (uint256 interimIssuer, uint256 interimQuadrata) = calculateSocialFees(_attribute);
we're not checking that msg.value is equal to interimIssuer + interimQuadrata

2023-01-06 18:56 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        (uint256 interimIssuer, uint256 interimQuadrata) = calculateSocialFees(_attribute);
Make sure to add unit tests with not enough ETH

2023-01-06 18:57 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        (uint256 interimIssuer, uint256 interimQuadrata) = calculateSocialFees(_attribute);
we're not checking that msg.value is equal to interimIssuer + interimQuadrata

2023-01-06 18:58 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        values[0] = attrs[0].value;
what happens if the attribute don't exist?

Will this throw?

2023-01-06 18:58 UTC, fabrice-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributesLegacy()', function() {
can we add a test for if the attribute don't exist

2023-01-06 18:58 UTC, fabrice-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributes()', function() {
can we add a test for if the attribute don't exist

2023-01-06 18:58 UTC, fabrice-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributesBulk()', function() {
can we add a test for if the attribute don't exist

2023-01-06 18:59 UTC, fabrice-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributesBulkLegacy()', function() {
can we add a test for if the attribute don't exist

2023-01-06 19:12 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    /// @dev Calculate the fees for issuer/quadrata
can we add a notice about the logic of calculating the fee for Quadrata?

2023-01-06 19:14 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        if(queryFeeMap[_attrName] / 2 > interimQuadFee) {
This logic is incorrect no??

Shouldn't this be something like.

if (queryFeeMap[_attrName] / 2 > quadrataFee) {
     interimIssuerFee = queryFeeMap[_attrName];
     interimQuadFee = queryFeeMap[_attrName]
} else {
    interimIssuerFee = queryFeeMap[_attrName];
    interimQuadFee = quadrataFee;
}

2023-01-06 19:15 UTC, fabrice-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +describe('SocialAttributeReader()', function() {
missing test on calculateSocialFee

2023-01-06 19:15 UTC, fabrice-quadrata requested changes
Left comments

2023-01-06 20:54 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        (uint256 interimIssuer, uint256 interimQuadrata) = calculateSocialFees(_attribute);
good find. thanks

2023-01-06 20:55 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        if(queryFeeMap[_attrName] / 2 > interimQuadFee) {
yes, good catch

2023-01-06 21:13 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        if(queryFeeMap[_attrName] / 2 > interimQuadFee) {
fixed

2023-01-06 21:13 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        (uint256 interimIssuer, uint256 interimQuadrata) = calculateSocialFees(_attribute);
Fixed

2023-01-06 21:56 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +    /// note The _sigAccount is a one-time use key (per attribute) to enable writing
fixed

2023-01-06 21:56 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        (uint256 interimIssuer, uint256 interimQuadrata) = calculateSocialFees(_attribute);
fixed w/ test

2023-01-06 21:56 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        (uint256 interimIssuer, uint256 interimQuadrata) = calculateSocialFees(_attribute);
added test

2023-01-09 17:45 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            interimIssuerFee = queryFeeMap[_attrName] / 2;
I think this is the full price actually

2023-01-09 17:45 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        if(queryFeeMap[_attrName] / 2 > quadrataFee) {
I think this should be if (queryFeeMap[_attrName] > quadrataFee)

2023-01-09 17:46 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            interimIssuerFee = queryFeeMap[_attrName] / 2;
I'd assume:
```
interimIssuerFee = queryFeeMap[_attrName];
intermQuadFee = interimIssuerFee;
```

2023-01-09 17:47 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +contract SocialAttributeReader is UUPSUpgradeable, ReentrancyGuardUpgradeable, QuadSocialAttributeReaderStore{
Can we rename the contract to FlexKit

2023-01-09 17:48 UTC, fabrice-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +contract SocialAttributeReader is UUPSUpgradeable, ReentrancyGuardUpgradeable, QuadSocialAttributeReaderStore{
Rename all reference to FlexKit

2023-01-09 19:36 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        if(queryFeeMap[_attrName] / 2 > quadrataFee) {
changed logic to just add the fees instead of doing all this division

2023-01-09 19:36 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +            interimIssuerFee = queryFeeMap[_attrName] / 2;
see below

2023-01-09 19:37 UTC, faze-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +describe('SocialAttributeReader()', function() {
removed calculate social fee. will add test for issuer withdrawal and assert correct balances

2023-01-09 19:37 UTC, faze-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributesBulkLegacy()', function() {
yes will add

2023-01-09 19:39 UTC, faze-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributesBulk()', function() {
none of these attributes exist in any of the tests

2023-01-09 19:46 UTC, faze-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributesBulk()', function() {
added

2023-01-09 19:46 UTC, faze-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +    it('succeeds with multiple attributes', async () => {
added

2023-01-09 19:46 UTC, faze-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributesBulkLegacy()', function() {
added

2023-01-09 19:47 UTC, faze-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributesLegacy()', function() {
added

2023-01-09 19:47 UTC, faze-quadrata commented on test/QuadSocialAttributeReader/test_social_attribute_reader.ts
> +  describe('getAttributes()', function() {
added

2023-01-09 19:47 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        values[0] = attrs[0].value;
no

2023-01-09 19:47 UTC, faze-quadrata commented on contracts/QuadSocialAttributeReader.sol
> +        values[0] = attrs[0].value;
returns empty attributre

2023-01-09 23:27 UTC, teddy-quadrata commented on contracts/QuadFlexKitReader.sol
> +import "hardhat/console.sol";
oops

2023-01-09 23:28 UTC, teddy-quadrata commented on contracts/QuadFlexKitReader.sol
> +import "@openzeppelin/contracts/utils/Strings.sol";
this is a really cool import. had no idea it contained string casts ops that we needed. good find

2023-01-09 23:31 UTC, teddy-quadrata commented on contracts/QuadFlexKitReader.sol
> +    function getAttributes(
if we are to easily measure the success of this "pilot" we probably want events so that we can look at metrics and monitor them

2023-01-09 23:32 UTC, fabrice-quadrata commented on contracts/QuadFlexKitReader.sol
> +contract QuadFlexKitReader is UUPSUpgradeable, ReentrancyGuardUpgradeable, QuadFlexKitReaderStore{
It's not just a Reader right?

Should we call it QuadFlexKit?

2023-01-10 01:08 UTC, faze-quadrata commented on contracts/QuadFlexKitReader.sol
> +contract QuadFlexKitReader is UUPSUpgradeable, ReentrancyGuardUpgradeable, QuadFlexKitReaderStore{
updated

2023-01-10 01:09 UTC, faze-quadrata commented on contracts/QuadFlexKitReader.sol
> +    function getAttributes(
added events for query/write attribute. let me know if you think others need it

2023-01-10 01:09 UTC, faze-quadrata commented on contracts/QuadFlexKitReader.sol
> +import "@openzeppelin/contracts/utils/Strings.sol";
👍

2023-01-10 23:27 UTC, fabrice-quadrata approved these changes

2023-01-10 23:53 UTC, teddy-quadrata approved these changes

2023-01-10 23:59 UTC, merged